services:
  db:
    image: mysql:8.0.36-debian
    container_name: moevents-db
    restart: always
    secrets:
      - root-password
      - moevents-password
    volumes:
      - data:/var/lib/mysql
    networks:
      - moevents
    environment:
      - MYSQL_DATABASE=moevents_db
      - MYSQL_ROOT_PASSWORD_FILE=run/secrets/root-password
      - MYSQL_USER=moevents
      - MYSQL_PASSWORD_FILE=run/secrets/moevents-password
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 256M

volumes:
  data:

secrets:
  root-password:
    file: docker/db/root.txt
  moevents-password:
    file: docker/db/moevents.txt

networks:
  moevents: